spring:
  datasource:
    username: osago
    password: uzb
    url: jdbc:oracle:thin:@10.10.1.204:1521:OSAGO


  servlet:
    multipart:
#      one file size
      max-file-size: 10MB
#      request size
      max-request-size: 50MB


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


#swagger uchun
springdoc:
  api-docs:
    path: /swagger.json
  swagger-ui:
    path: /swagger



#tokenni amal qilish muddati (sutkalarda)
token:
  expiration:
    time: 720
  #security key token
  security:
    key: Kapital123Sugurta

#serverdagi errorlarni korsatishi uchun
server:
  error:
    include-binding-errors: always
  port: 8080
